# Generated by Django 5.0.4 on 2024-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['sort'], 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Категорія страв', 'verbose_name_plural': 'Категорії страв'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['sort'], 'verbose_name': 'Захід', 'verbose_name_plural': 'Заходи'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Категорія заходів', 'verbose_name_plural': 'Категорії заходів'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['sort'], 'verbose_name': 'Категорія галереї', 'verbose_name_plural': 'Категорії галереї'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['sort'], 'verbose_name': 'Зображення галереї', 'verbose_name_plural': 'Зображення галереї'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['sort'], 'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Категорія персоналу', 'verbose_name_plural': 'Категорії персоналу'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='title',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='Default Name', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(default='Default Name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffcategory',
            name='name',
            field=models.CharField(default='Default Name', max_length=255, unique=True),
        ),
    ]
