# Generated by Django 5.0.4 on 2024-04-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_options_alter_dishcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffcategory',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
