# Generated by Django 5.0.4 on 2024-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_title_event_name_dishcategory_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
