# Generated by Django 5.0.4 on 2024-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gallery_remove_galleryimage_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Захід',
                'verbose_name_plural': 'Заходи',
                'ordering': ['sort'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
