# Generated by Django 5.0.4 on 2024-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events_delete_event_delete_eventcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='category',
        ),
        migrations.DeleteModel(
            name='StaffCategory',
        ),
    ]
