# Generated by Django 5.0.4 on 2024-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_staff_category_delete_staffcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
