# Generated by Django 5.0.4 on 2024-04-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_events_photo_events_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['sort'], 'verbose_name': 'Подія', 'verbose_name_plural': 'ПодіЇ'},
        ),
    ]
